notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2015

#MSVC
#install:
#  - git submodule update --init --recursive
#  - set QTDIR=C:\Qt\5.9\msvc2015
#  - set PATH=%PATH%;%QTDIR%\bin
install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

#MSVC
#build_script:
#  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
#  - qmake signal.pro
#  - dir
#  - nmake
#  - dir
build_script:
  - qmake signal.pro
  - mingw32-make

after_build:
  - cd release
  - copy "%QTDIR%\bin\libgcc_s_dw2-1.dll" .
  - copy "%QTDIR%\bin\libstdc++-6.dll" .
  - copy "%QTDIR%\bin\libwinpthread-1.dll" .
  - windeployqt --no-compiler-runtime --no-translations --release signal.exe
  - ps : rm *.cpp
  - ps : rm *.h
  - ps : rm *.o
  - ps : rm *.obj
  - dir

artifacts:
  - path: release
    name: signal
  - path: release/signal.exe
    name: signal.exe
